version: '3.4'

services:
    app:
        image: nginx:stable-alpine
        container_name: nginx-proxy
        restart: unless-stopped
        volumes:
            - ./public_html/:/public_html
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./dhparam/:/etc/nginx/dhparam
            - ./certbot/conf/:/etc/nginx/ssl
            - ./certbot/data/:/usr/share/nginx/html/letsencrypt
        ports:
            - 80:80
            - 443:443
    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email eqbal@prohukum.com --agree-tos --no-eff-email -d chikidev2.hopto.org
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/logs:/var/log/letsencrypt
            - ./certbot/data:/usr/share/nginx/html/letsencrypt
